#!/bin/bash
# skip if empty
set -e
if [ "$(mpc playlist | wc -l)" -eq 0 ]; then
    notify-send "Add songs"
    exit 1
fi

# cleanup
rm -rf ~/.cache/songs; mkdir ~/.cache/songs; cd ~/.cache/songs
rm ~/.local/share/mpd/playlists/songs.m3u; mpc -q save songs

# rsync server
RSYNC_SERVER="sync@10.0.0.3:/storage/emulated/0/Music"

# copy to phone
rsync -avL --files-from="$HOME/.local/share/mpd/playlists/songs.m3u" ~/.local/share/.Music "$RSYNC_SERVER"
rsync -av ~/.cache/songs/ "$RSYNC_SERVER"
mpc -q clear
